name       : vlc
version    : 2.2.6
release    : 36
source     :
    - https://download.videolan.org/pub/videolan/vlc/2.2.6/vlc-2.2.6.tar.xz : c403d3accd9a400eb2181c958f3e7bc5524fe5738425f4253d42883b425a42a8
license    :
    - LGPL-2.1
    - GPL-2.0
component  : multimedia.video
summary    : Open source multimedia player
description: |
    VLC is a free and open source cross-platform multimedia player and framework that plays most multimedia files as well as DVDs, Audio CDs, VCDs, and various streaming protocols.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(avahi-client)
    - pkgconfig(dbus-1)
    - pkgconfig(dcadec)
    - pkgconfig(dvdnav)
    - pkgconfig(dvdread)
    - pkgconfig(freetype2)
    - pkgconfig(fribidi)
    - pkgconfig(gl)
    - pkgconfig(gnutls)
    - pkgconfig(gstreamer-app-1.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(kate)
    - pkgconfig(flac)
    - pkgconfig(libaacs)
    - pkgconfig(libass)
    - pkgconfig(libavcodec)
    - pkgconfig(libbluray)
    - pkgconfig(libcddb)
    - pkgconfig(libdc1394-2)
    - pkgconfig(libdvbpsi)
    - pkgconfig(libidn)
    - pkgconfig(libmatroska)
    - pkgconfig(libmodplug)
    - pkgconfig(libmpeg2)
    - pkgconfig(libmtp)
    - pkgconfig(libnotify)
    - pkgconfig(libnotify)
    - pkgconfig(libpulse)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libssh2)
    - pkgconfig(libupnp)
    - pkgconfig(libva-drm)
    - pkgconfig(lua-5.1)
    - pkgconfig(ogg)
    - pkgconfig(opus)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(samplerate)
    - pkgconfig(sdl)
    - pkgconfig(SDL_image)
    - pkgconfig(shout)
    - pkgconfig(smbclient)
    - pkgconfig(sndfile)
    - pkgconfig(speexdsp)
    - pkgconfig(taglib)
    - pkgconfig(theora)
    - pkgconfig(twolame)
    - pkgconfig(vdpau)
    - pkgconfig(vorbis)
    - pkgconfig(vpx)
    - pkgconfig(x264)
    - pkgconfig(x265)
    - pkgconfig(xcb)
    - pkgconfig(xcb-composite)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcb-xv)
    - pkgconfig(xext)
    - pkgconfig(xi)
    - pkgconfig(xinerama)
    - pkgconfig(xpm)
    - pkgconfig(xproto)
    - libmad-devel
    - liba52dec-devel
    - libgcrypt-devel
    - libjpeg-turbo-devel
    - live-media-devel
    - faad-devel
setup      : |
    sed -i "s|lua5.1|lua-5.1|g" configure
    %patch -p1 < $pkgfiles/vlc-2.2.4-ffmpeg3-1.patch
    CXXFLAGS+=" -std=gnu++98"
    %configure --disable-rpath \
               --enable-a52 \
               --enable-bluray \
               --enable-dvbpsi \
               --enable-dvdnav \
               --enable-dvdread \
               --enable-faad \
               --enable-fontconfig \
               --enable-gst-decode \
               --enable-kate \
               --enable-libass \
               --enable-libmpeg2 \
               --enable-libva \
               --enable-mad \
               --enable-realrtsp \
               --enable-shout \
               --enable-twolame \
               --enable-vpx \
               --enable-x264 \
               --enable-x265
build      : |
    CXXFLAGS+=" -std=gnu++98"
    %make
install    : |
    CXXFLAGS+=" -std=gnu++98"
    %make_install
