name       : vlc
version    : 2.2.8
release    : 44
source     :
    - https://download.videolan.org/pub/videolan/vlc/2.2.8/vlc-2.2.8.tar.xz : 9bf046848fb56d93518881b39099b8288ee005d5ba0ddf705b6f6643b8d562ec
license    :
    - LGPL-2.1
    - GPL-2.0
component  : multimedia.video
summary    : Open source multimedia player
description: |
    VLC is a free and open source cross-platform multimedia player and framework that plays most multimedia files as well as DVDs, Audio CDs, VCDs, and various streaming protocols.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(avahi-client)
    - pkgconfig(dbus-1)
    - pkgconfig(dcadec)
    - pkgconfig(dvdnav)
    - pkgconfig(fribidi)
    - pkgconfig(gl)
    - pkgconfig(gnutls)
    - pkgconfig(gstreamer-app-1.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(kate)
    - pkgconfig(flac)
    - pkgconfig(libaacs)
    - pkgconfig(libass)
    - pkgconfig(libavcodec)
    - pkgconfig(libbluray)
    - pkgconfig(libcddb)
    - pkgconfig(libdc1394-2)
    - pkgconfig(libdvbpsi)
    - pkgconfig(libidn2)
    - pkgconfig(libmatroska)
    - pkgconfig(libmodplug)
    - pkgconfig(libmpeg2)
    - pkgconfig(libmtp)
    - pkgconfig(libnotify)
    - pkgconfig(libpulse)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libssh2)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libupnp)
    - pkgconfig(libva-drm)
    - pkgconfig(lua-5.3)
    - pkgconfig(opus)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(samplerate)
    - pkgconfig(SDL_image)
    - pkgconfig(shout)
    - pkgconfig(smbclient)
    - pkgconfig(sndfile)
    - pkgconfig(speexdsp)
    - pkgconfig(taglib)
    - pkgconfig(theora)
    - pkgconfig(twolame)
    - pkgconfig(vdpau)
    - pkgconfig(vorbis)
    - pkgconfig(vpx)
    - pkgconfig(x264)
    - pkgconfig(x265)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xext)
    - pkgconfig(xi)
    - pkgconfig(xpm)
    - pkgconfig(xproto)
    - faad-devel
    - liba52dec-devel
    - libgcrypt-devel
    - libmad-devel
    - live-media-devel
setup      : |
    %patch -p1 < $pkgfiles/use-gnu-libidn2-library.patch
    %patch -p1 < $pkgfiles/lua53_compat.patch
    %patch -p1 < $pkgfiles/vlc-2.2.4-ffmpeg3-1.patch
    %patch -p1 < $pkgfiles/vlc-gcc6-buildfixes.patch
    %patch -p1 < $pkgfiles/fix-atomics-usage-in-cpp.patch
    export CXXFLAGS+=" -std=c++11 -Wno-unknown-pragmas"
    %configure --disable-rpath \
               --enable-a52 \
               --enable-bluray \
               --enable-dvbpsi \
               --enable-dvdnav \
               --enable-dvdread \
               --enable-faad \
               --enable-fontconfig \
               --enable-gst-decode \
               --enable-kate \
               --enable-libass \
               --enable-libmpeg2 \
               --enable-libva \
               --enable-mad \
               --enable-realrtsp \
               --enable-sftp \
               --enable-shout \
               --enable-twolame \
               --enable-vpx \
               --enable-x264 \
               --enable-x265
build      : |
    export CXXFLAGS+=" -std=c++11 -Wno-unknown-pragmas"
    %make
install    : |
    export CXXFLAGS+=" -std=c++11 -Wno-unknown-pragmas"
    %make_install
