name       : vlc
version    : 2.2.4
release    : 20
source     :
    - http://download.videolan.org/pub/videolan/vlc/2.2.4/vlc-2.2.4.tar.xz : 1632e91d2a0087e0ef4c3fb4c95c3c2890f7715a9d1d43ffd46329f428cf53be
license    :
    - LGPL-2.1
    - GPL-2.0
component  : multimedia.video
summary    : Open source multimedia player
description: |
    VLC is a free and open source cross-platform multimedia player and framework that plays most multimedia files as well as DVDs, Audio CDs, VCDs, and various streaming protocols.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(dbus-1)
    - pkgconfig(dvdread)
    - pkgconfig(dvdnav)
    - pkgconfig(freetype2)
    - pkgconfig(fribidi)
    - pkgconfig(gl)
    - pkgconfig(gnutls)
    - pkgconfig(gstreamer-app-1.0)
    - pkgconfig(libaacs)
    - pkgconfig(libass)
    - pkgconfig(libavcodec)
    - pkgconfig(libbluray)
    - pkgconfig(libidn)
    - pkgconfig(libmodplug)
    - pkgconfig(libnotify)
    - pkgconfig(libupnp)
    - pkgconfig(libpulse)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libva-drm)
    - pkgconfig(lua-5.1)
    - pkgconfig(opus)
    - pkgconfig(Qt5Core)
    - pkgconfig(sdl2)
    - pkgconfig(SDL2_image)
    - pkgconfig(sndfile)
    - pkgconfig(speexdsp)
    - pkgconfig(taglib)
    - pkgconfig(vdpau)
    - pkgconfig(vorbis)
    - pkgconfig(theora)
    - pkgconfig(ogg)
    - pkgconfig(kate)
    - pkgconfig(libmpeg2)
    - pkgconfig(twolame)
    - pkgconfig(shout)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(vpx)
    - pkgconfig(x264)
    - pkgconfig(xcb)
    - pkgconfig(xcb-composite)
    - pkgconfig(xcb-xv)
    - pkgconfig(xinerama)
    - pkgconfig(xext)
    - pkgconfig(xpm)
    - pkgconfig(xproto)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libnotify)
    - pkgconfig(libmtp)
    - pkgconfig(dcadec)
    - pkgconfig(libcddb)
    - libmad-devel
    - liba52dec-devel
    - libgcrypt-devel
    - libjpeg-turbo-devel
    - faad-devel
setup      : |
    %configure --disable-rpath \
               --enable-a52 \
               --enable-faad \
               --enable-vpx \
               --enable-twolame \
               --enable-libva \
               --enable-gst-decode \
               --enable-mad \
               --enable-shout \
               --enable-dvdread \
               --enable-dvdnav \
               --enable-bluray \
               --enable-libmpeg2 \
               --enable-x264 \
               --enable-fontconfig \
               --enable-kate \
               --enable-libass
build      : |
    %make
install    : |
    %make_install
