name       : vlc
version    : 3.0.4
release    : 72
source     :
    - https://download.videolan.org/pub/videolan/vlc/3.0.4/vlc-3.0.4.tar.xz : 01f3db3790714038c01f5e23c709e31ecd6f1c046ac93d19e1dde38b3fc05a9e
license    :
    - LGPL-2.1-or-later
    - GPL-2.0-or-later
component  : multimedia.video
summary    : Open source multimedia player
description: |
    VLC is a free and open source cross-platform multimedia player and framework that plays most multimedia files as well as DVDs, Audio CDs, VCDs, and various streaming protocols.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(avahi-client)
    - pkgconfig(dbus-1)
    - pkgconfig(dcadec)
    - pkgconfig(dvdnav)
    - pkgconfig(flac)
    - pkgconfig(fluidsynth)
    - pkgconfig(fribidi)
    - pkgconfig(gl)
    - pkgconfig(gnutls)
    - pkgconfig(gstreamer-app-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(kate)
    - pkgconfig(libaacs)
    - pkgconfig(libarchive)
    - pkgconfig(libass)
    - pkgconfig(libavcodec)
    - pkgconfig(libbluray)
    - pkgconfig(libcddb)
    - pkgconfig(libchromaprint)
    - pkgconfig(libdc1394-2)
    - pkgconfig(libdvbpsi)
    - pkgconfig(libidn2)
    - pkgconfig(libmatroska)
    - pkgconfig(libmodplug)
    - pkgconfig(libmpeg2)
    - pkgconfig(libmtp)
    - pkgconfig(libnotify)
    - pkgconfig(libpulse)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libssh2)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libupnp)
    - pkgconfig(libva-drm)
    - pkgconfig(lua-5.3)
    - pkgconfig(microdns)
    - pkgconfig(opus)
    - pkgconfig(protobuf-lite)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(samplerate)
    - pkgconfig(SDL_image)
    - pkgconfig(shout)
    - pkgconfig(smbclient)
    - pkgconfig(sndfile)
    - pkgconfig(speexdsp)
    - pkgconfig(taglib)
    - pkgconfig(theora)
    - pkgconfig(twolame)
    - pkgconfig(vdpau)
    - pkgconfig(vorbis)
    - pkgconfig(vpx)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
    - pkgconfig(x264)
    - pkgconfig(x265)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xext)
    - pkgconfig(xi)
    - pkgconfig(xpm)
    - pkgconfig(xproto)
    - faad-devel
    - liba52dec-devel
    - libgcrypt-devel
    - libmad-devel
    - live-media-devel
setup      : |
    export BUILDCC="$CC"
    export CFLAGS="$CFLAGS -std=c99"
    %patch -p1 < $pkgfiles/lua53_compat.patch
    %patch -p1 < $pkgfiles/x264-modern.patch
    %patch -p1 < $pkgfiles/vlc-qt5.11.patch
    %configure --disable-rpath \
               --enable-a52 \
               --enable-bluray \
               --enable-dvbpsi \
               --enable-dvdnav \
               --enable-dvdread \
               --enable-faad \
               --enable-fontconfig \
               --enable-gst-decode \
               --enable-kate \
               --enable-libass \
               --enable-libmpeg2 \
               --enable-libva \
               --enable-mad \
               --enable-realrtsp \
               --enable-sftp \
               --enable-shout \
               --enable-twolame \
               --enable-vpx \
               --enable-wayland \
               --enable-x264 \
               --enable-x265 \
               --enable-microdns
build      : |
    %make
install    : |
    %make_install

    # Don't install solbuild generated plugins cache file,
    # It's unusable and vlc will run fine without it. See T5893.
    # vlc-cache-gen needs to be run on the actual host system
    rm $installdir/usr/lib64/vlc/plugins/plugins.dat
