name       : vlc
version    : 2.2.1
release    : 10
source     :
    - http://download.videolan.org/pub/videolan/vlc/2.2.1/vlc-2.2.1.tar.xz : 543d9d7e378ec0fa1ee2e7f7f5acf8c456c7d0ecc32037171523197ef3cf1fcb
license    :
    - LGPL-2.1
    - GPL-2.0
summary    : Open source multimedia player
description: |
    VLC is a free and open source cross-platform multimedia player and framework that plays most multimedia files as well as DVDs, Audio CDs, VCDs, and various streaming protocols.
clang      : no
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(dbus-1)
    - pkgconfig(dvdread)
    - pkgconfig(dvdnav)
    - pkgconfig(freetype2)
    - pkgconfig(fribidi)
    - pkgconfig(gl)
    - pkgconfig(gnutls)
    - pkgconfig(gstreamer-app-1.0)
    - pkgconfig(libaacs)
    - pkgconfig(libass)
    - pkgconfig(libavcodec)
    - pkgconfig(libbluray)
    - pkgconfig(libidn)
    - pkgconfig(libmodplug)
    - pkgconfig(libnotify)
    - pkgconfig(libupnp)
    - pkgconfig(libpulse)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libva-drm)
    - pkgconfig(lua-5.1)
    - pkgconfig(Qt5Core)
    - pkgconfig(sdl2)
    - pkgconfig(SDL2_image)
    - pkgconfig(speexdsp)
    - pkgconfig(taglib)
    - pkgconfig(vdpau)
    - pkgconfig(vorbis)
    - pkgconfig(vpx)
    - pkgconfig(x264)
    - pkgconfig(xcb)
    - pkgconfig(xcb-composite)
    - pkgconfig(xcb-xv)
    - pkgconfig(xinerama)
    - pkgconfig(xext)
    - pkgconfig(xpm)
    - pkgconfig(xproto)
    - libmad-devel
    - liba52dec-devel
    - libgcrypt-devel
setup      : |
    %configure --disable-rpath
build      : |
    %make
install    : |
    %make_install
