name       : vlc
version    : 2.2.2
release    : 14
source     :
    - http://download.videolan.org/pub/videolan/vlc/2.2.2/vlc-2.2.2.tar.xz : 9ad23128be16f9b40ed772961272cb0748ed8e4aa1bc79c129e589feebea5fb5
license    :
    - LGPL-2.1
    - GPL-2.0
summary    : Open source multimedia player
description: |
    VLC is a free and open source cross-platform multimedia player and framework that plays most multimedia files as well as DVDs, Audio CDs, VCDs, and various streaming protocols.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(dbus-1)
    - pkgconfig(dvdread)
    - pkgconfig(dvdnav)
    - pkgconfig(freetype2)
    - pkgconfig(fribidi)
    - pkgconfig(gl)
    - pkgconfig(gnutls)
    - pkgconfig(gstreamer-app-1.0)
    - pkgconfig(libaacs)
    - pkgconfig(libass)
    - pkgconfig(libavcodec)
    - pkgconfig(libbluray)
    - pkgconfig(libidn)
    - pkgconfig(libmodplug)
    - pkgconfig(libnotify)
    - pkgconfig(libupnp)
    - pkgconfig(libpulse)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libva-drm)
    - pkgconfig(lua-5.1)
    - pkgconfig(opus)
    - pkgconfig(Qt5Core)
    - pkgconfig(sdl2)
    - pkgconfig(SDL2_image)
    - pkgconfig(speexdsp)
    - pkgconfig(taglib)
    - pkgconfig(vdpau)
    - pkgconfig(vorbis)
    - pkgconfig(theora)
    - pkgconfig(ogg)
    - pkgconfig(kate)
    - pkgconfig(libmpeg2)
    - pkgconfig(twolame)
    - pkgconfig(shout)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(vpx)
    - pkgconfig(x264)
    - pkgconfig(xcb)
    - pkgconfig(xcb-composite)
    - pkgconfig(xcb-xv)
    - pkgconfig(xinerama)
    - pkgconfig(xext)
    - pkgconfig(xpm)
    - pkgconfig(xproto)
    - libmad-devel
    - liba52dec-devel
    - libgcrypt-devel
    - libjpeg-turbo-devel
setup      : |
    %configure --disable-rpath
build      : |
    %make
install    : |
    %make_install
