description = "Generate the VLC plugins cache"

[check]
paths = [
    "/usr/lib64/vlc/plugins/"
]

[skip]
chroot = true
live = true

[[bins]]
task = "Generating the VLC plugins cache"
bin = "/usr/lib64/vlc/vlc-cache-gen"
args = [
    "/usr/lib64/vlc/plugins/"
]
